CREATE TABLE `ACCOUNT` (
	`ACCOUNT_NUM`	VARCHAR(255)	NOT NULL,
	`USERNAME`	VARCHAR(255)	NOT NULL,
	`PRODUCT_NUM`	BIGINT	NOT NULL,
	`ACCOUNT_DATE`	DATE	NULL,
	`ACCOUNT_BALANCE`	BIGINT	NULL
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `PK_ACCOUNT` PRIMARY KEY (
	`ACCOUNT_NUM`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_MEMBER_TO_ACCOUNT_1` FOREIGN KEY (
	`USERNAME`
)
REFERENCES `MEMBER` (
	`USERNAME`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_PRODUCT_TO_ACCOUNT_1` FOREIGN KEY (
	`PRODUCT_NUM`
)
REFERENCES `PRODUCT` (
	`PRODUCT_NUM`
);

