CREATE TABLE `CART` (
	`USERNAME`	VARCHAR(255)	NOT NULL,
	`PRODUCT_NUM`	BIGINT	NOT NULL
);

ALTER TABLE `CART` ADD CONSTRAINT `FK_MEMBER_TO_CART_1` FOREIGN KEY (
	`USERNAME`
)
REFERENCES `MEMBER` (
	`USERNAME`
);

ALTER TABLE `CART` ADD CONSTRAINT `FK_PRODUCT_TO_CART_1` FOREIGN KEY (
	`PRODUCT_NUM`
)
REFERENCES `PRODUCT` (
	`PRODUCT_NUM`
);

ALTER TABLE `CART` ADD CONSTRAINT `PK_CART` PRIMARY KEY (
	`USERNAME`, `PRODUCT_NUM`
);

