CREATE TABLE `MEMBER` (
	`USER_NAME`	VARCHAR(255)	NOT NULL,
	`PASSWORD`	VARCHAR(255)	NULL,
	`NAME`	VARCHAR(255)	NULL,
	`EMAIL`	VARCHAR(255)	NULL,
	`PHONE`	VARCHAR(255)	NULL,
	`BIRTH`	DATE	NULL
);

CREATE TABLE `PROFILE` (
	`USER_NAME`	VARCHAR(255)	NOT NULL,
	`SAVE_NAME`	VARCHAR(255)	NULL,
	`ORI_NAME`	VARCHAR(255)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`USER_NAME`
);

ALTER TABLE `PROFILE` ADD CONSTRAINT `PK_PROFILE` PRIMARY KEY (
	`USER_NAME`
);

ALTER TABLE `PROFILE` ADD CONSTRAINT `FK_MEMBER_TO_PROFILE_1` FOREIGN KEY (
	`USER_NAME`
)
REFERENCES `MEMBER` (
	`USER_NAME`
);

