CREATE TABLE `MEMBER` (
	`USER_NAME`	VARCHAR(255)	NOT NULL,
	`PASSWORD`	VARCHAR(255)	NULL,
	`NAME`	VARCHAR(255)	NULL,
	`EMAIL`	VARCHAR(255)	NULL,
	`PHONE`	VARCHAR(255)	NULL,
	`BIRTH`	DATE	NULL
);

CREATE TABLE `PROFILE` (
	`USER_NAME`	VARCHAR(255)	NOT NULL,
	`SAVE_NAME`	VARCHAR(255)	NULL,
	`ORI_NAME`	VARCHAR(255)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`USER_NAME`
);

ALTER TABLE `PROFILE` ADD CONSTRAINT `PK_PROFILE` PRIMARY KEY (
	`USER_NAME`
);

ALTER TABLE `PROFILE` ADD CONSTRAINT `FK_MEMBER_TO_PROFILE_1` FOREIGN KEY (
	`USER_NAME`
)
REFERENCES `MEMBER` (
	`USER_NAME`
);

ALTER TABLE `MEMBER`
ADD `ACCOUNT_NON_EXPIRED`	BIT	DEFAULT 1,
ADD `ACCOUNT_NON_LOCKED`	BIT	DEFAULT 1,
ADD `CREDENTIAL_NON_EXPIRED`	BIT	DEFAULT 1,
ADD `ENABLED`	BIT	DEFAULT 1;

-- -------------------- ROLE

CREATE TABLE `ROLE` (
	`ROLE_NUM`	BIGINT	NOT NULL,
	`ROLE_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `MEMBER_ROLE` (
	`USERNAME`	VARCHAR(255)	NOT NULL,
	`ROLE_NUM`	BIGINT	NOT NULL
);

ALTER TABLE `ROLE` ADD CONSTRAINT `PK_ROLE` PRIMARY KEY (
	`ROLE_NUM`
);

ALTER TABLE `ROLE` MODIFY `ROLE_NUM` BIGINT AUTO_INCREMENT;

ALTER TABLE `MEMBER_ROLE` ADD CONSTRAINT `PK_MEMBER_ROLE` PRIMARY KEY (
	`USERNAME`, `ROLE_NUM`
);

ALTER TABLE `MEMBER_ROLE` ADD CONSTRAINT `FK_MEMBER_TO_MEMBER_ROLE_1` FOREIGN KEY (
	`USERNAME`
)
REFERENCES `MEMBER` (
	`USERNAME`
);

ALTER TABLE `MEMBER_ROLE` ADD CONSTRAINT `FK_ROLE_TO_MEMBER_ROLE_1` FOREIGN KEY (
	`ROLE_NUM`
)
REFERENCES `ROLE` (
	`ROLE_NUM`
);

-- ROLE
-- ROLE_ADMIN
-- ROLE_MANAGER
-- ROLE_MEMBER

INSERT INTO ROLE (ROLE_NAME)
VALUES ('ROLE_ADMIN'),
	('ROLE_MANAGER'),
	('ROLE_MEMBER');


SELECT *
FROM PROFILE;

SELECT *
FROM MEMBER AS m
JOIN PROFILE AS p USING (USERNAME)
JOIN MEMBER_ROLE AS r USING (USERNAME)
WHERE USERNAME = 'user1';

INSERT INTO MEMBER_ROLE
VALUES
	('admin', 2),
	('admin', 3);