CREATE TABLE `NOTICE_FILES` (
	`FILE_NUM`	BIGINT	NOT NULL,
	`ORI_NAME`	VARCHAR(255)	NULL,
	`SAVE_NAME`	VARCHAR(255)	NULL,
	`BOARD_NUM`	BIGINT	NOT NULL
);

ALTER TABLE `NOTICE_FILES` ADD CONSTRAINT `PK_NOTICE_FILES` PRIMARY KEY (
	`FILE_NUM`
);

ALTER TABLE user01.notice_files MODIFY COLUMN FILE_NUM bigint AUTO_INCREMENT NOT NULL;

ALTER TABLE user01.notice_files ADD CONSTRAINT notice_files_notice_FK 
FOREIGN KEY (BOARD_NUM) REFERENCES user01.notice(BOARD_NUM);
