-- user01.notice definition

CREATE TABLE `NOTICE` (
  `BOARD_NUM` bigint NOT NULL AUTO_INCREMENT,
  `BOARD_TITLE` varchar(255) DEFAULT NULL,
  `BOARD_CONTENT` longtext,
  `BOARD_WRITER` varchar(255) DEFAULT NULL,
  `BOARD_DATE` datetime DEFAULT NULL,
  `BOARD_HIT` bigint DEFAULT NULL,
  PRIMARY KEY (`BOARD_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `NOTICE_FILES` (
	`FILE_NUM`	BIGINT	NOT NULL,
	`ORI_NAME`	VARCHAR(255)	NULL,
	`SAVE_NAME`	VARCHAR(255)	NULL,
	`BOARD_NUM`	BIGINT	NOT NULL
);

ALTER TABLE `NOTICE_FILES` ADD CONSTRAINT `PK_NOTICE_FILES` PRIMARY KEY (
	`FILE_NUM`
);

ALTER TABLE user01.NOTICE_FILES MODIFY COLUMN FILE_NUM bigint AUTO_INCREMENT NOT NULL;

ALTER TABLE user01.NOTICE_FILES ADD CONSTRAINT notice_files_notice_FK 
FOREIGN KEY (BOARD_NUM) REFERENCES user01.notice(BOARD_NUM);
