create table PRODUCT_KIND (
	KIND_NUM BIGINT AUTO_INCREMENT
	, KIND_NAME VARCHAR(255)
    , PRIMARY KEY (KIND_NUM)
);

alter table PRODUCTS_KIND add constraint PK_PRODUCTS_KIND primary key (
	KIND_NUM
);

create table PRODUCT (
	PRODUCT_NUM BIGINT AUTO_INCREMENT
	, PRODUCT_NAME VARCHAR(255)
	, PRODUCT_CONTENTS LONGTEXT
	, PRODUCT_DATE DATETIME
	, PRODUCT_RATE DECIMAL(4, 2)
	, KIND_NUM BIGINT
    , PRIMARY KEY (PRODUCT_NUM)
    , FOREIGN KEY (KIND_NUM) REFERENCES PRODUCT_KIND(KIND_NUM)
);

alter table PRODUCTS add constraint PK_PRODUCTS primary key (
	PRODUCT_NUM 
);

alter table PRODUCTS add constraint FK_PRODUCTS foreign key (PRODUCT_KIND)
references PRODUCTS_KIND(KIND_NUM);

INSERT INTO product_kind (kind_name)
values ('예금')
	, ('적금')
    , ('대출');
    
    
INSERT INTO product
VALUES (NULL, '상품명', '상품 내용', '2027-12-31', 1.12, 1);

SELECT *
FROM PRODUCT
ORDER BY PRODUCT_NUM DESC;

SELECT *
FROM PRODUCT_KIND
WHERE KIND_NUM = 1;

SELECT *
FROM PRODUCT_KIND
WHERE KIND_NUM = (
	SELECT KIND_NUM
	FROM PRODUCT
	WHERE PRODUCT_NUM = 1
);

SELECT *
-- SELECT p.*, k.*
FROM PRODUCT AS p
JOIN PRODUCT_KIND AS k
-- ON p.KIND_NUM = k.KIND_NUM
USING (KIND_NUM)
WHERE p.PRODUCT_NUM = 1;








