
CREATE TABLE `QNA` (
  `BOARD_NUM` BIGINT NOT NULL AUTO_INCREMENT,
  `BOARD_TITLE` VARCHAR(255) DEFAULT NULL,
  `BOARD_CONTENT` LONGTEXT,
  `BOARD_WRITER` VARCHAR(255) DEFAULT NULL,
  `BOARD_DATE` DATETIME DEFAULT NULL,
  `BOARD_HIT` BIGINT DEFAULT NULL,
  `BOARD_REF` BIGINT,
  `BOARD_STEP` BIGINT,
  `BOARD_DEPTH` BIGINT,
  PRIMARY KEY (`BOARD_NUM`)
) ENGINE = InnoDB AUTO_INCREMENT = 8 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


SELECT *
FROM QNA
ORDER BY BOARD_REF DESC, BOARD_STEP;
